# Generated by Django 2.1.5 on 2019-02-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата приема на работу', models.DateField(blank=True, null=True)),
                ('Зарплата', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Отдел', models.CharField(max_length=100)),
                ('Должность', models.CharField(max_length=45)),
                ('Начальник', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.FIO')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Должность',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ФИО',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.FIO'),
        ),
    ]
